djangoProject5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('top10.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

top10/urls.py
from django.urls import path

from . import views

app_name = 'top10'

urlpatterns = [
    path('', views.index, name='index'),
    path('tech', views.tech, name = 'tech'),
    path('post/<slug:post_slug>/', views.detail, name = 'detail'),
    path('post/<slug:post_slug>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('finance', views.finance, name = 'finance'),
    path('health', views.health, name = 'health'),
    path('lifestyle', views.lifestyle, name='lifestyle'),
    path('family', views.family, name='family'),
    path('business', views.business, name='business'),
    path('shopping', views.shopping, name='shopping'),
    path('entertainment', views.entertainment, name='entertainment'),
    path('personal_growth', views.personal_growth, name='personal_growth'),
    path('register/', views.registerPage, name='register'),
    path('log-in/', views.logIn, name='log-in'),
    path('log-out/', views.logOut, name='log-out')
]

top10/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Category(models.Model):
    category_name = models.CharField('Category', max_length=50)
    category_title = models.CharField('Category title', max_length=100, null=True)
    def __str__(self):
        return self.category_name



class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    CHOISES = (
        ("Must read" , "Must read"),
        ("Hot this week", 'Hot this week'),
        ("Trending", 'Trending')
    )
    importance = models.CharField(max_length=200, null=True, choices=CHOISES)


    subject = models.CharField('Titlte', max_length=200)
    item_name = models.CharField('Post item name(What kind of items will be appear in this post)', max_length=200,
                                 null=True)
    title_description = models.CharField('TittleDescription', max_length=400)
    picture_main = models.ImageField(upload_to="gallery")
    post_description = RichTextField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    slug = models.SlugField(null=True, unique=True)
    def __str__(self):
        return self.subject


class PostItem(models.Model):
    choises = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    )

    subject = models.ForeignKey(Post, on_delete=models.CASCADE)
    item_title = models.CharField('Item title', max_length=500)
    item_name = models.CharField('ItemName', max_length=50)
    item_description = models.CharField('ItemDescription', max_length=50)
    item_picture = models.ImageField(upload_to="gallery")
    item_link = models.CharField('Link', max_length=400)
    place_in_top = models.IntegerField(choices=choises, default='1')

    description = RichTextField()

    def __str__(self):
        return self.item_name


class Pros(models.Model):
    item_name = models.ForeignKey(PostItem, on_delete=models.CASCADE)
    pros_title = models.CharField('Pros', max_length=200)

    def __str__(self):
        return self.pros_title


class Cons(models.Model):
    item_name = models.ForeignKey(PostItem, on_delete=models.CASCADE)
    cons_title = models.CharField('Cons', max_length=200)

    def __str__(self):
        return self.cons_title


class Benefits(models.Model):
    item_name = models.ForeignKey(PostItem, on_delete=models.CASCADE)
    benefit_title = models.CharField('Benefit title', max_length=200)
    benefit_desc = models.CharField('Benefit description', max_length=200)

    def __str__(self):
        return self.benefit_title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_name = models.ForeignKey(User, editable=False, on_delete=models.CASCADE)
    comment_text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


class TableRow(models.Model):
    post_name = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    table_row = models.CharField('Table row', max_length=200, null=True)


class TableValue(models.Model):
    post_item = models.ForeignKey(PostItem, on_delete=models.CASCADE, null=True)
    table_value = models.CharField('Table value', max_length=200, null=True)

    def __str__(self):
        return self.table_value

templates/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from top10.models import Comment
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'top10/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'top10/tech.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'top10/log-in.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'top10/register.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'top10/detail.css' %}">
{#    <link rel="shortcut icon" type="x-icon" href="{% static 'top10/img/favicon.ico' %}"/>#}
    <title> {% block title %} {% endblock %} </title>
</head>
<body>

    <div class="container-fluid">
        <header class="blog-header py-3 navigation-bar">
            <div class="row">
              <div class="col-3 d-flex justify-content-center align-items-center">
                   {% if user.is_authenticated %}
                       <h4 class="text-white">Hello, {{ request.user }} </h4>
                  {% endif %}
              </div>
              <div class="col-6 d-flex justify-content-center align-items-center">
                    <img src="{% static 'top10/img/logo-white.png' %}" height="100px">
              </div>
              <div class="col-3 d-flex justify-content-center align-items-center">
                      {% if user.is_authenticated %}
                          <a href="{% url 'top10:log-out' %}" class="btn btn-info"><i class="fas fa-sign-out-alt"></i></a>
                      {% else %}
                          <a class="btn btn-sm btn-outline-light sign-up-button" href="{% url 'top10:log-in' %}">Sign up</a>
                      {% endif %}
              </div>
            </div>
      </header>
    </div>
    <div class="container">
        <div class="nav-scroller py-1 mb-5">
                <nav class="shift">
                <ul>

                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:index' %}"><i class="fas fa-home"></i> Home</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:tech' %}"><i class="fas fa-server"></i> Tech</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:finance' %}"><i class="fas fa-money-check-alt"></i> Finances</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:health' %}"><i class="fas fa-file-medical"></i> Health</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:lifestyle' %}"><i class="fas fa-hand-spock"></i> Lifestyle</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:family' %}"><i class="fas fa-child"></i> Family</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:business' %}"><i class="fas fa-business-time"></i> Business Tools</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:shopping' %}"><i class="fas fa-tags"></i> Shopping</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:entertainment' %}"><i class="fas fa-gamepad"></i> Entertainment</a></li>
                  <li><a class="p-2 text-muted navbar-link ltr" style="text-decoration: none;" href="{% url 'top10:personal_growth' %}"><i class="fas fa-level-up-alt"></i> Personal Growth</a></li>
                </ul>
                </nav>
              </div>

        {% block content %} {% endblock %}
    </div>





























</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block title %}{{ main_post.subject }} {% endblock %}

{% block content %}


<div class="container-fluid mb-5 header-container">
    <div class="row">
        <div class="col-3">
            <div class="jumbotron">
                <div class="row mb-3">
                    <div class="col-12 d-flex justify-content-start align-items-center">
                        <h5> Jump to : </h5>
                    </div>
                </div>
                <hr>
            {% for i in output %}
                <div class="row mb-3">
                    {{ i.place_in_top }}. <a href="#{{ i.item_name }}" class="text-info pl-2" style="white-space: nowrap">{{ i.item_name }}</a>
                </div>
             {% endfor %}
            </div>
        </div>
        <div class="col-9">
            <img src="{{ main_post.picture_main.url }}" width="100%" height="100%">
                <div class="text-block-image">
                    <div class="container-fluid">
                        <div class="row text-row-header">
                            <div class="col-12 d-flex justify-content-center align-items-center">
                                <h1><b> {{ main_post.title_description }}</b></h1>
                            </div>
                        </div>

                            <h6 class="text-info date-of-post">Post was created {{ main_post.date_created }}</h6>
                    </div>
                </div>
        </div>
    </div>
</div>
    <table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
          <th scope="col">#</th>
            <th scope="col">{{ main_post.item_name }}</th>
                {% for x in main_post.tablerow_set.all %}

                    <th scope="col"> {{ x.table_row }} </th>

                 {% endfor %}


    </tr>
  </thead>
  <tbody>
    {% for i in output %}
        <tr>
          <th scope="row">{{ i.place_in_top }}</th>
          <td>{{ i.item_name  }}</td>
            {% for x in i.tablevalue_set.all %}
                <td>{{ x.table_value }} </td>

            {% endfor %}
        </tr>
    {% endfor %}
  </tbody>
</table>
    <div class="container">
        <div class="row">
            <div class="card" style="border: 0;">
                <div class="card-body">
                    {{  main_post.post_description | safe}}
                </div>
            </div>
        </div>

    </div>



    {% if output %}
        {% for i in output %}
            <div class="row" id="{{ i.item_name }}">
                <div class="col-1 d-flex align-items-center">
                    <h1>{{ i.place_in_top }}.</h1>
                </div>
                <div class="col-9 d-flex justify-content-start align-items-center">
                    <h3> {{ i.item_name }} </h3>
                </div>
            </div>
            <div class="row">
                <div class="col-11 offset-1 d-flex justify-content-start align-items-center pl-4 text-secondary">
                    <h4> {{ i.item_title }} </h4>
                </div>
            </div>
            <div class="row">
                <div class="col-12 d-flex justify-content-center align-items-center">
                    <div class="card" style="border: 0">
                         <img class="card-img-top" src="{{ i.item_picture.url }}" alt="Card image cap" style="width: auto; height: 500px; border: 0;">
                    </div>
                </div>
            </div>
            <hr>
            <div class="row mb-5">
                <h4> Benefits: </h4>
                {% for ben in i.benefits_set.all %}
                    <div class="col-12 d-flex justify-content-start align-items-center">
                        <h5 class="text-success"><i class="fas fa-check pr-3"></i>{{ ben.benefit_title }} - {{ ben.benefit_desc }}</h5>
                    </div>
                {% endfor %}
            </div>
            <div class="card" style="border: 0;">
                <div class="card-body">
                    {{  i.description | safe}}
                </div>
            </div>

            <div class="row mt-3 post-pre-footer">

                <div class="col-6 d-flex justify-content-center align-items-center">
                    <h4> {{ i.item_name }} </h4>
                </div>
                <div class="col-6 d-flex justify-content-center align-items-center">
                    <a type="button" class="btn btn-info" href="{{ i.item_link }}"> Go to website </a>
                </div>

            </div>


            <div class="row mb-5">
                <div class="col-6">
                    <h4> Pros : </h4>
                    <ul class="list-group list-group-flush">
                        {% for pr in i.pros_set.all %}
                            <li class="list-group-item "><i class="fas fa-check text-success pr-3"></i>{{ pr.pros_title }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-6">
                    <h4> Cons : </h4>
                    <ul class="list-group list-group-flush">
                        {% for co in i.cons_set.all %}
                            <li class="list-group-item"><i class="fas fa-times text-danger pr-3"></i>{{ co.cons_title }}</li>
                        {% endfor %}
                    </ul>
                </div>

            </div>


        {% endfor %}

        {##}
        <div class="jumbotron mt-5">
            <div class="row">
                <div class="col-4 d-flex align-items-center">
                    <h3 class="text-info">Total comments {{ comments_count }}</h3>
                </div>
                <div class="col-8 d-flex align-items-center justify-content-end">
                    <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#commentsCollapse" aria-expanded="false" aria-controls="commentsCollapse" > Show comments </button>
                </div>
            </div>
            <div class="collapse" id="commentsCollapse">
                {% for i in comments %}
                <div class="card card-body mt-3">
                    <p>User <b class="text-info">{{ i.user_name }}</b> says.. </p>
                    <h4> {{ i.comment_text }} </h4>
                </div>

                {% endfor %}
            </div>
        </div>



        {% if user.is_authenticated %}

                    <form action="{% url 'top10:leave_comment' post_slug %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group mt-5">
                            <textarea name="text" required class="form-control" placeholder="Enter comment here "></textarea>
                        </div>
                        <div class="col-12 d-flex justify-content-end align-items-center">
                            <button type="submit" class="btn btn-info mt-3 mb-5">Leave a comment</button>
                        </div>
                    </form>
        {% else %}
            <div class="alert alert-warning mb-5" role="alert">
                <h4> If you want to leave or see the comment please log-in or sign-up !</h4>
            </div>

        {% endif %}

    {% else %}
            <h1> No top right now wait until admin will create it  </h1>
    {% endif %}

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Welocme to Top10.com {% endblock %}


{% block content %}

        {% if output %}
            <div class="row mb-5">
                <div class="col-9">
                    <div class="card">
                        <div class="card-body">
                            <a href="{% url 'top10:detail' output.id %}" class="navbar-link ltr card-link" style="text-decoration: none;"><h5 class="card-title">{{ output.subject }}</h5></a>
                            <p class="card-text">{{ output.title_description }}</p>
                            <p class="card-text">Created - {{ output.date_created }}</p>
                        </div>
                        <img class="card-img-bottom" src="{{ output.picture_main.url}}" alt="Card image">
                    </div>
                </div>
                <div class="col-3">
                    <div class="card  must-read-card">
                        <div class="card-body">
                            <h5 class="card-title">Must read: </h5>
                            {% for i in posts %}
                                {% if i.importance == 'Must read' %}
                                    <a href="{% url 'top10:detail' i.id %}" class="text-dark"> {{ i.subject }}</a>
                                {% else %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card must-read-card mt-3">
                        <div class="card-body">
                            <h5 class="card-title">Hot this week: </h5>
                            {% for i in posts %}
                                {% if i.importance == 'Hot this week' %}
                                    <a href="{% url 'top10:detail' i.id %}" class="text-dark"> {{ i.subject }}</a>
                                {% else %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-12 d-flex justify-content-start align-items-center">
                    <h1>Top trending lists:</h1>
                </div>

            </div>
            {% for i in posts %}

                {% if i.importance == 'Trending' %}
                    <hr>
                    <div class="row">

                        <div class="col-1 d-flex justify-content-center align-items-center">
                            <h1> <i class="far fa-check"></i></h1>
                        </div>
                        <div class="col-7 d-flex justify-content-start align-items-center">
                            <h4><b><a class=" text-muted" href="#">{{ i.subject }}</a></b></h4>
                        </div>
                        <div class="col-4 d-flex justify-content-end align-items-center">
                            <img src="{{ i.picture_main.url }}" alt="preview" height="150px" width="75%">
                        </div>

                    </div>
                    {% else %}
                {% endif %}
            {% endfor %}

        {% else %}
            <h1> Sorry no posts right now </h1>
        {% endif %}


{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Sign-up {% endblock %}



{% block content %}
    <div class="wrapper fadeInDown mt-3">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <form method="POST" action="">
        {% csrf_token %}
    <div class="fadeIn first"> <h4> <i class="fa fa-user"></i> Please sign-up to check all our posts</h4>

    </div>

      <div class="row mt-5 mb-5">

          <div class="col-8 offset-2">
                <input type="text" class="form-control" placeholder="Username" name="username">
          </div>

      </div>
      <div class="row mt-5 mb-5">

          <div class="col-8 offset-2">
                <input type="password" class="form-control" placeholder="Password" name="password">
          </div>

      </div>


      <div class="row mt-5 mb-5">

          <div class="col-8 offset-2">
                <button type="submit" class="btn btn-info"> Log in </button>
          </div>

      </div>
    </form>


    <!-- Remind Passowrd -->
    <div id="formFooter">
        <div class="row">
            <div class="col-12 d-flex justify-content-center align-items-center">
                {% for message in messages %}
                    <p id="messages"> {{ message }} </p>
                 {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12 d-flex justify-content-center align-items-center">
                <a class="underlineHover" href="{% url 'top10:register' %}">No account? Register</a>
            </div>
        </div>
       <div class="row">
            <div class="col-12 d-flex justify-content-center align-items-center">
                <a class="underlineHover" href="#">Forgot Password?</a>
            </div>
        </div>

    </div>

  </div>
</div>
 {% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block content %}
<div class="card bg-light">
<article class="card-body mx-auto" style="max-width: 400px;">
	<h4 class="card-title mt-3 text-center">Create Account</h4>
	<p class="text-center">Get started with your free account</p>

	<form method="POST" action="">
        {% csrf_token %}
	<div class="form-group input-group">
		<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		 </div>
                {{ form.username }}
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
		 </div>
                {{ form.email }}
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
            {{ form.password1 }}
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
            {{ form.password2 }}
    </div> <!-- form-group// -->
    <div class="form-group">
        <button type="submit" class="btn btn-info btn-block"> Create Account  </button>
    </div> <!-- form-group// -->
    <p class="text-center">Have an account? <a href="{% url 'top10:log-in' %}">Log In</a> </p>
</form>
    {{ form.errors }}
</article>
</div>
    <script>

    const form_fields = document.getElementsByTagName("input")
    form_fields[1].placeholder='Username..'
    form_fields[2].placeholder='Email..'
    form_fields[3].placeholder='Password..'
    form_fields[4].placeholder='Repeat password..'

    for (let field in form_fields) {
        form_fields[field].className += 'form-control'
    }

    </script>
{% endblock %}

templates/tech.html
{% extends 'base.html' %}

{% block title %} Top10 | Technologies {% endblock %}

{% block content %}
    {% for i in category %}
        <h1 class="display 4"> {{ i.category_title }} </h1>
     {% endfor %}
    <div class="row">
    <div class="col-9">
    {% if output %}
        {% for a in output %}

            <div class="card mb-5 mt-5">
              <img class="card-img-top" src="{{ a.picture_main.url }}" alt="Card image cap">
              <div class="card-body">
              <h5 class="card-title"><a href="{% url 'top10:detail' a.slug %}" class="text-secondary">{{a.subject}}</a></h5>
                <p class="card-text">{{a.title_description}}</p>
                <p class="card-text"><small class="text-muted">{{ a.date_created }}</small></p>
              </div>
            </div>

        {% endfor %}
                </div>
        <div class="col-3">
                         <div class="card  must-read-card" style="height: 400px">
                        <div class="card-body">
                            <h3 class="card-title">Why <b class="text-info">Top10</b> your decision</h3>
                            <div class="card-body">
                                <h5 class="text-info"> Compare </h5>
                                <p class="mb-3"> We find 10 best options.</p>
                                <h5 class="text-info"> Choose </h5>
                                <p class="mb-3"> So you make decisions with ease.</p>
                                <h5 class="text-info"> Celebrate </h5>
                                <p class="mb-3"> Simple right?</p>
                            </div>
                        </div>
                    </div>
                                 <div class="card  must-read-card mt-3" style="height: 1150px">
                        <div class="card-body">
                            <h5 class="card-title">10 Steps to Shopping With Confidence : </h5>
                            <div class="card-body">
                               <p class="card-text"><b>01 Hope, dream, think:</b> What need will the purchase solve?</p>
                                <p class="card-text"><b>02 Determine:</b> What aspects of product can be compared?</p>
                                <p class="card-text"><b>03 Research: </b> Who are the leading brands? What od they offer?</p>
                                <p class="card-text"><b>04 Consider: </b> Which features are most important for you?</p>
                                <p class="card-text"><b>05 Read, watch, consult: </b> What do the reviews say? What do experts recommend?</p>
                                <p class="card-text"><b>06 Compare: </b> How do the brands on your shortlist stack up head-to-head?</p>
                                <p class="card-text"><b>07 Check prices: </b> What special deals can you take advantage of></p>
                                <p class="card-text"><b>08 Read the fine print: </b>Are you comfortable with the terms and condition offered?</p>
                                <p class="card-text"><b>09 Choose confidently: </b> Once you've followed these steps - you should be ready to buy.</p>
                                <p class="card-text"><b>10 Trust: </b> You have made an educated decision that responds to your needs.</p>
                            </div>
                        </div>
                    </div>
        </div>
            </div>
    {% else %}
        <h1> Wait until admin would create some posts... </h1>
    {% endif %}

{% endblock %}